const app=document.getElementById('app');
let progress={},trainee='',trainingContent=[],currentPage={group:'home'},editing=null,saveQueue=Promise.resolve();
const META='__boh_edit__:';
const OVERALL_STATUS='__boh_overall_trained__';
function overallTrained(p){return p[OVERALL_STATUS]===true;}
function personStatusHtml(name,p){return `<label class="field">${esc(name)} — Overall BOH training<select class="trainer-name overall-status" data-status="${overallTrained(p)?'trained':'in-training'}" aria-label="${esc(name)} overall BOH training" onchange="saveOverallStatus(${arg(name)},this.value==='trained',this)"><option value="in-training" ${!overallTrained(p)?'selected':''}>In Training</option><option value="trained" ${overallTrained(p)?'selected':''}>Trained</option></select></label><p class="small" role="status"></p>`;}
async function saveOverallStatus(name,value,select){select.dataset.status=value?'trained':'in-training';select.disabled=true;const status=select.parentElement.nextElementSibling;status.textContent='Saving…';let oldValue=!value;const operation=saveQueue.then(async()=>{const rows=await request('boh_training?team_member=eq.'+encodeURIComponent(name)+'&select=id,progress');if(!rows.length)throw new Error('This team member could not be found. Refresh and try again.');const merged=rows.reduce((p,row)=>({...p,...row.progress}),{});oldValue=overallTrained(merged);merged[OVERALL_STATUS]=value;await request('boh_training?id=eq.'+encodeURIComponent(rows[0].id),{method:'PATCH',body:JSON.stringify({progress:merged})});if(trainee===name)progress[OVERALL_STATUS]=value;status.textContent='Saved.';});saveQueue=operation.catch(error=>{select.value=oldValue?'trained':'in-training';status.textContent=error.message;}).finally(()=>{select.dataset.status=select.value;select.disabled=false;});return saveQueue;}
const WELCOME={title:'Welcome & Restaurant Tour',sections:[['Welcome',['Clock In','Restaurant Tour']]]};
function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');}
function arg(s){return esc(JSON.stringify(s));}
function idFor(group,slug,item){return `${group}:${slug}:${item}`;}
async function request(path,options={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...options,headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json',...options.headers}});if(!r.ok)throw new Error('Unable to save or load. Please try again. ('+r.status+')');if(r.status===204)return null;const text=await r.text();return text?JSON.parse(text):null;}
async function loadTrainingContent(){const rows=await request('training_content?select=*&order=sort_order.asc');if(!Array.isArray(rows))throw new Error('Training data could not be loaded.');trainingContent=rows;}
function report(error){alert(error.message||'Something went wrong. Please try again.');}
async function run(action){try{await action();}catch(error){report(error);}}
function base(group,slug){return group==='station'?STATIONS[slug]:group==='closing'?CLOSING[slug]:WELCOME;}
function meta(key){const row=trainingContent.find(x=>x.title===META+key&&x.item_type==='category');if(!row)return {};try{return JSON.parse(row.description||'{}');}catch{return {};}}
async function putMeta(key,value,group,slug,subsection=''){const title=META+key;const old=trainingContent.find(x=>x.title===title&&x.item_type==='category');const body={section:group,category:group==='closing'?'closing':slug,subsection,title,description:JSON.stringify(value),item_type:'category',sort_order:-1};await request(old?'training_content?id=eq.'+encodeURIComponent(old.id):'training_content',{method:old?'PATCH':'POST',body:JSON.stringify(body)});await loadTrainingContent();}
function pageTitle(group,slug){return meta('page:'+group+':'+slug).title||base(group,slug).title;}
function sectionTitle(group,slug,title){return meta('section:'+group+':'+slug+':'+title).title||title;}
function extraRows(group,slug){return trainingContent.filter(x=>x.item_type!=='category'&&x.section===group&&x.category===(group==='closing'?'closing':slug));}
function pageSections(group,slug){const result=base(group,slug).sections.map(([title,items])=>({key:title,items:items.map(original=>{const key=idFor(group,slug,original),m=meta('item:'+key);return {key,title:m.title??(group==='station'&&slug==='food-safety'?FOOD_SAFETY_TITLES[original]||original:original),description:m.description??(group==='station'&&slug==='food-safety'?FOOD_SAFETY_DETAILS[original]||'':group==='station'&&slug==='rsa-assessment'?RSA_ASSESSMENT_DETAILS[original]||'':''),link_url:m.link_url||'',hidden:!!m.hidden,original};})}));for(const row of extraRows(group,slug)){let section=row.subsection||'Additional Training';if(group==='closing'){if(row.subsection?.includes('::')){const [area,...parts]=row.subsection.split('::');if(area!==slug)continue;section=parts.join('::');}else if(slug!=='boards')continue;}let target=result.find(x=>x.key===section);if(!target){target={key:section,items:[]};result.push(target);}target.items.push({key:'content:'+row.id,title:row.title,description:row.description||'',link_url:row.link_url||'',rowId:row.id,hidden:!!meta('hidden:'+row.id).hidden});}return result;}
function pageItems(group,slug){return pageSections(group,slug).flatMap(s=>s.items).filter(x=>!x.hidden);}
function allIds(){return [...Object.keys(STATIONS).flatMap(slug=>pageItems('station',slug)),...Object.keys(CLOSING).flatMap(slug=>pageItems('closing',slug))].map(x=>x.key);}
function safeLink(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
function controls(group,slug){return `<div class="edit-actions"><button onclick="run(()=>editPageTitle(${arg(group)},${arg(slug)}))">Edit page title</button><button onclick="editTraining()">Edit Training</button></div>`;}
function home(){currentPage={group:'home'};app.innerHTML=`<h1>BOH Training</h1><p class="sub">Training reference and shared progress tracker.</p><div class="menu home-menu"><button class="primary" onclick="welcome()">${esc(pageTitle('welcome','welcome'))}</button>${Object.keys(STATIONS).map(k=>`<button onclick="station(${arg(k)})">${esc(pageTitle('station',k))}</button>`).join('')}<button onclick="closingMenu()">Closing</button><button onclick="progressView()">My Progress</button><button onclick="run(()=>addTeamMember(prompt('Enter team member name')))">Add Team Member</button><button onclick="allProgress()">All Progress</button><button onclick="editTraining()">Edit Training</button></div>`;}
async function openPage(group,slug){await run(async()=>{await loadTrainingContent();currentPage={group,slug};renderPage(group,slug);});}
function welcome(){return openPage('welcome','welcome');}
function station(slug){return openPage('station',slug);}
function closingPage(slug){return openPage('closing',slug);}
const FSA_ASSESSMENT_TITLES = new Set(['Cross-contamination Part 1','Cross-contamination Part 2','Health & Hygiene Part 1','Health & Hygiene Part 2','Cleaning & Sanitation Part 1','Cleaning & Sanitation Part 2','Time & Temperature Part 1','Time & Temperature Part 2','Pests']);

const FSA_CHECK_STORAGE='boh_fsa_walkthrough_v1';
let fsaChecks={};
try{const saved=JSON.parse(localStorage.getItem(FSA_CHECK_STORAGE)||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))fsaChecks=saved;}catch{}
function fsaCheckState(item){const saved=fsaChecks[item.key];return saved&&saved.description===item.description&&Array.isArray(saved.checked)?saved.checked:[];}
function fsaCheckCount(item){return item.description.split('\n').filter(line=>/^\s*•\s/.test(line)).length;}
function fsaCheckStatus(item,saved=true){const checked=fsaCheckState(item),lines=item.description.split('\n');const count=lines.reduce((n,line,i)=>n+(/^\s*•\s/.test(line)&&checked.includes(i)?1:0),0);return count+' of '+fsaCheckCount(item)+' checked · '+(saved?'Saved on this device':'Could not save for reopening');}
function fsaChecklistHtml(item){const checked=fsaCheckState(item);return `<div class="fsa-checklist" data-fsa-key="${esc(item.key)}"><p class="fsa-help">Check each item during this walkthrough. Clear checks to start the next assessment.</p><div class="fsa-check-actions"><button type="button" onclick="clearFsaChecks(${arg(item.key)},this)">Clear checks</button><span class="small fsa-check-status" role="status">${esc(fsaCheckStatus(item))}</span></div>${item.description.split('\n').map((line,index)=>/^\s*•\s/.test(line)?`<label class="fsa-checkrow"><input type="checkbox" ${checked.includes(index)?'checked':''} onchange="toggleFsaCheck(${arg(item.key)},${index},this.checked,this)"><span>${esc(line.replace(/^\s*•\s*/,''))}</span></label>`:line.trim()?`<p class="fsa-check-text ${/^SDC\./.test(line)?'fsa-check-heading':''}">${esc(line)}</p>`:'').join('')}</div>`;}
function storeFsaChecks(){try{localStorage.setItem(FSA_CHECK_STORAGE,JSON.stringify(fsaChecks));return true;}catch{return false;}}
function toggleFsaCheck(key,index,value,input){const item=pageItems('station','food-safety').find(x=>x.key===key);if(!item)return;const checked=new Set(fsaCheckState(item));if(value)checked.add(index);else checked.delete(index);fsaChecks[key]={description:item.description,checked:[...checked]};const saved=storeFsaChecks();input.closest('.fsa-checklist').querySelector('.fsa-check-status').textContent=fsaCheckStatus(item,saved);}
function clearFsaChecks(key,button){const item=pageItems('station','food-safety').find(x=>x.key===key);if(!item)return;delete fsaChecks[key];const saved=storeFsaChecks();const card=button.closest('.fsa-checklist');card.querySelectorAll('input[type="checkbox"]').forEach(input=>input.checked=false);card.querySelector('.fsa-check-status').textContent=fsaCheckStatus(item,saved);}

function itemHtml(group,slug,section,item,showHidden=false){if(item.hidden&&!showHidden)return '';const link=safeLink(item.link_url);const isFsaCard=group==='station'&&slug==='food-safety'&&FSA_ASSESSMENT_TITLES.has(item.title);const isAssessmentCard=slug==='rsa-assessment'||isFsaCard;return `<div class="training-item"><label class="checkrow"><input type="checkbox" ${progress[item.key]?'checked':''} ${item.hidden||!trainee?'disabled':''} onchange="toggle(${arg(item.key)},this.checked)"><span>${esc(item.title)}${item.hidden?' (deleted)':''}${item.description&&!isAssessmentCard?`<small class="item-description">${esc(item.description)}</small>`:''}</span></label>${item.description&&isAssessmentCard?`<details class="assessment-card"><summary>View assessment card</summary>${isFsaCard?fsaChecklistHtml(item):`<div class="item-description">${esc(item.description)}</div>`}${isFsaCard&&link?`<a class="item-link" href="${esc(link)}" target="_blank" rel="noopener">Open Link</a>`:''}</details>`:''}${link&&!isFsaCard?`<a class="item-link" href="${esc(link)}" target="_blank" rel="noopener">Open Link</a>`:''}<div class="edit-actions"><button onclick="openItemEditor(${arg(group)},${arg(slug)},${arg(section)},${arg(item.key)})">Edit</button><button onclick="run(()=>hideItem(${arg(group)},${arg(slug)},${arg(item.key)},${!item.hidden}))">${item.hidden?'Restore':'Delete'}</button></div></div>`;}
function renderPage(group,slug,showHidden=false){app.innerHTML=`<h1>${esc(pageTitle(group,slug))}</h1><p class="sub">${trainee?'Team member: '+esc(trainee):'Select a team member in Trainer View to record training status.'}</p>${controls(group,slug)}${pageSections(group,slug).map(s=>`<div class="section"><div class="section-heading"><h2>${esc(sectionTitle(group,slug,s.key))}</h2><button onclick="run(()=>editSectionTitle(${arg(group)},${arg(slug)},${arg(s.key)}))">Edit heading</button></div>${s.items.map(x=>itemHtml(group,slug,s.key,x,showHidden)).join('')}<button class="add-item" onclick="openItemEditor(${arg(group)},${arg(slug)},${arg(s.key)},null)">Add Item</button></div>`).join('')}`;}
function closingMenu(){currentPage={group:'closingMenu'};app.innerHTML=`<h1>Closing</h1><p class="sub">Choose a closing area.</p><div class="menu">${Object.keys(CLOSING).map(k=>`<button onclick="closingPage(${arg(k)})">${esc(pageTitle('closing',k))}</button>`).join('')}</div>`;}
function categories(){return [['welcome','welcome',pageTitle('welcome','welcome')],...Object.keys(STATIONS).map(k=>['station',k,pageTitle('station',k)]),...Object.keys(CLOSING).map(k=>['closing',k,pageTitle('closing',k)])];}
async function editTraining(selection){await run(async()=>{await loadTrainingContent();currentPage={group:'editor',selection:selection||'welcome|welcome'};app.innerHTML=`<h1>Edit Training</h1><p class="sub">Edit titles, section headings, instructions, and links. Hidden items can be restored here.</p><select id="editCategory" class="trainer-name" onchange="renderEditCategory()">${categories().map(([g,k,title])=>`<option value="${g}|${k}" ${g+'|'+k===currentPage.selection?'selected':''}>${esc(title)}</option>`).join('')}</select><div id="editItems"></div>`;renderEditCategory();});}
function renderEditCategory(){const selection=document.getElementById('editCategory').value;currentPage={group:'editor',selection};const [g,k]=selection.split('|');document.getElementById('editItems').innerHTML=`<button onclick="run(()=>editPageTitle(${arg(g)},${arg(k)}))">Edit page title</button>${pageSections(g,k).map(s=>`<div class="section"><div class="section-heading"><h2>${esc(sectionTitle(g,k,s.key))}</h2><button onclick="run(()=>editSectionTitle(${arg(g)},${arg(k)},${arg(s.key)}))">Edit heading</button></div>${s.items.map(x=>itemHtml(g,k,s.key,x,true)).join('')}<button class="add-item" onclick="openItemEditor(${arg(g)},${arg(k)},${arg(s.key)},null)">Add Item</button></div>`).join('')}`;}
async function refreshPage(){if(currentPage.group==='editor')return editTraining(currentPage.selection);if(['welcome','station','closing'].includes(currentPage.group))return openPage(currentPage.group,currentPage.slug);home();}
async function editPageTitle(group,slug){const title=prompt('Page title',pageTitle(group,slug));if(title===null||!title.trim())return;await putMeta('page:'+group+':'+slug,{title:title.trim()},group,slug);await refreshPage();}
async function editSectionTitle(group,slug,section){const title=prompt('Section heading',sectionTitle(group,slug,section));if(title===null||!title.trim())return;await putMeta('section:'+group+':'+slug+':'+section,{title:title.trim()},group,slug,section);await refreshPage();}
function openItemEditor(group,slug,section,key){const item=key?pageSections(group,slug).flatMap(s=>s.items).find(x=>x.key===key):null;editing={group,slug,section,key,item,returnPage:{...currentPage}};app.innerHTML=`<h1>${item?'Edit':'Add'} Training Item</h1><form id="itemForm" onsubmit="event.preventDefault();run(saveItemEditor)"><label class="field">Title<input id="itemTitle" required value="${esc(item?.title||'')}"></label><label class="field">Instructions<textarea id="itemDescription" rows="6">${esc(item?.description||'')}</textarea></label><label class="field">Link (optional)<input id="itemLink" type="url" placeholder="https://" value="${esc(item?.link_url||'')}"></label><div class="edit-actions"><button class="save-item" id="saveItemButton" type="submit">Save Changes</button><button type="button" onclick="cancelItemEditor()">Cancel</button></div><p id="editorStatus" role="status"></p></form>`;}
async function cancelItemEditor(){currentPage=editing.returnPage;editing=null;await refreshPage();}
async function saveItemEditor(){const e=editing,title=document.getElementById('itemTitle').value.trim(),description=document.getElementById('itemDescription').value.trim(),link_url=document.getElementById('itemLink').value.trim();if(!title)throw new Error('Enter a title.');if(link_url&&!safeLink(link_url))throw new Error('Use an http or https link.');const button=document.getElementById('saveItemButton');button.disabled=true;document.getElementById('editorStatus').textContent='Saving…';try{if(e.item?.original!==undefined){await putMeta('item:'+e.key,{...meta('item:'+e.key),title,description,link_url},e.group,e.slug,e.section);}else{const body={section:e.group,category:e.group==='closing'?'closing':e.slug,subsection:e.group==='closing'?e.slug+'::'+e.section:e.section,title,description,link_url,item_type:link_url?'link':'item',sort_order:999};await request(e.item?'training_content?id=eq.'+encodeURIComponent(e.item.rowId):'training_content',{method:e.item?'PATCH':'POST',body:JSON.stringify(body)});await loadTrainingContent();}currentPage=e.returnPage;editing=null;await refreshPage();}catch(error){button.disabled=false;document.getElementById('editorStatus').textContent=error.message;throw error;}}
async function hideItem(group,slug,key,hidden){const item=pageSections(group,slug).flatMap(s=>s.items).find(x=>x.key===key);if(!item)return;if(hidden&&!confirm('Delete this item from training? You can restore it in Edit Training.'))return;if(item.original!==undefined)await putMeta('item:'+key,{...meta('item:'+key),hidden},group,slug);else await putMeta('hidden:'+item.rowId,{hidden},group,slug);await refreshPage();}
async function addTeamMember(name){name=(name||'').trim();if(!name)return;const rows=await request('boh_training?team_member=eq.'+encodeURIComponent(name)+'&select=id');if(!rows.length)await request('boh_training',{method:'POST',body:JSON.stringify({team_member:name,progress:{}})});await setTrainee(name);await trainer();}
async function loadRemote(){if(!trainee){progress={};return;}const rows=await request('boh_training?team_member=eq.'+encodeURIComponent(trainee)+'&select=progress');progress=rows.reduce((all,row)=>({...all,...row.progress}),{});}
async function setTrainee(name){const previous=trainee;await saveQueue;trainee=(name||'').trim();try{await loadRemote();}catch(error){trainee=previous;throw error;}}
function toggle(key,value){if(!trainee){refreshPage();alert('Select a team member in Trainer View first.');return Promise.resolve();}const previous=progress[key];progress[key]=value;const name=trainee;const operation=saveQueue.then(async()=>{const rows=await request('boh_training?team_member=eq.'+encodeURIComponent(name)+'&select=id,progress');const merged=rows.reduce((p,row)=>({...p,...row.progress}),{});merged[key]=value;if(rows.length)await request('boh_training?id=eq.'+encodeURIComponent(rows[0].id),{method:'PATCH',body:JSON.stringify({progress:merged})});else await request('boh_training',{method:'POST',body:JSON.stringify({team_member:name,progress:merged})});});saveQueue=operation.catch(error=>{if(trainee===name&&progress[key]===value){progress[key]=previous;if(['welcome','station','closing'].includes(currentPage.group))renderPage(currentPage.group,currentPage.slug);else if(currentPage.group==='editor')renderEditCategory();}report(error);});return saveQueue;}
function prog(title,items,p){const n=items.filter(x=>p[x.key]).length,t=items.length,pct=t?Math.round(n/t*100):0;return `<div class="card"><h2>${esc(title)}</h2><div class="progressbar"><span style="width:${pct}%"></span></div><div class="small">${n} of ${t} trained · ${pct}%</div></div>`;}
async function progressView(){await run(async()=>{await saveQueue;await loadTrainingContent();await loadRemote();currentPage={group:'progress'};app.innerHTML=`<h1>My Progress</h1><p>Team member: <b>${esc(trainee||'Not selected')}</b></p>${trainee?personStatusHtml(trainee,progress):''}${Object.keys(STATIONS).map(k=>prog(pageTitle('station',k),pageItems('station',k),progress)).join('')}${Object.keys(CLOSING).map(k=>prog(pageTitle('closing',k),pageItems('closing',k),progress)).join('')}<button onclick="trainer()">Open training checklists</button>`;});}
async function selectPerson(name){await run(async()=>{await setTrainee(name);await trainer();});}
async function allProgress(){await run(async()=>{await saveQueue;await loadTrainingContent();const rows=await request('boh_training?select=team_member,progress&order=team_member.asc'),people=new Map();rows.forEach(x=>{if(x.team_member)people.set(x.team_member,{...people.get(x.team_member),...x.progress});});const ids=allIds();currentPage={group:'allProgress'};app.innerHTML=`<h1>All Progress</h1><p class="sub">Choose one overall BOH training status for each team member.</p>${Array.from(people,([name,p])=>`<div class="card">${personStatusHtml(name,p)}<div class="menu"><button onclick="selectPerson(${arg(name)})">Open ${esc(name)}’s progress — ${ids.length?Math.round(ids.filter(id=>p[id]).length/ids.length*100):0}%</button></div></div>`).join('')}`;});}
async function trainer(){await run(async()=>{await saveQueue;await loadTrainingContent();await loadRemote();const rows=await request('boh_training?select=team_member&order=team_member.asc'),names=[...new Set(rows.map(x=>x.team_member).filter(Boolean))];currentPage={group:'trainer'};app.innerHTML=`<h1>Trainer View</h1><p class="sub">Select a team member to record shared training status.</p><select class="trainer-name" onchange="selectPerson(this.value)"><option value="">Select team member</option>${names.map(name=>`<option value="${esc(name)}" ${name===trainee?'selected':''}>${esc(name)}</option>`).join('')}</select>${trainee?personStatusHtml(trainee,progress):''}<div class="menu">${Object.keys(STATIONS).map(k=>`<button onclick="station(${arg(k)})">${esc(pageTitle('station',k))}</button>`).join('')}<button onclick="closingMenu()">Closing</button><button onclick="progressView()">View Progress</button></div>`;});}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>({learn:home,progress:progressView,trainer}[b.dataset.nav])());document.getElementById('homeBtn').onclick=home;home();loadTrainingContent().then(()=>{if(currentPage.group==='home')home();}).catch(()=>{});
